import Head from 'next/head'
import Image from 'next/image'
import '../styles/Home.module.css'


export async function getStaticProps() {
  const github = await fetch('https://next-api-liard.vercel.app/api')
  const gitResponse = await github.json()
  return {
    props: { gitResponse }

  }

}


export default function Home({ gitResponse }) {

  function handleClick() {
    window.location.href = '/api'
  }


  return (
    <div className="container"
    >
      <Head>
        <title>Meu App Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <h1>
        {gitResponse.dateTime}
      </h1>
      <main className="main">
        <div className="grid">
<<<<<<< HEAD
          <div className="card cardPerfil">
            <div>
              <div className='card-image'>
                <img
                  src={gitResponse.Avatar}
                  alt="avatar - Gabriel Fernandes"
                  className="avatar"
                />
              </div>
              <h2>{gitResponse.Name} </h2>
              <p className='cardP'>{gitResponse.Bio} </p>
              <p>{gitResponse.Blog} </p>
              <p>{gitResponse.Email} </p>
              <p>repositorios: {gitResponse.Repos} </p>
              <p>Seguidores: {gitResponse.Followers} </p>
              <p>seguindo: {gitResponse.Following} </p>
            </div>
          </div>
          <aside className="aside">
            <h1
              className="title"
              id="title"
            >
              <a href=''
                onClick={handleClick}
                target="_blank">
                Bem vindo a minha Api!
              </a>
            </h1>
            <div className="title">
              <button
                onClick={handleClick}
                className="button"
                target="_blank">
                Api aqui!
              </button>
            </div>
            <div className="aside-content grid">

              <div className="card">
                <p className='cardP'>
                  Esse é um exemplo de uma API que foi criada com Next.js.
                </p>
                <p className='cardP'>
                  Uma api que retorna dados de um usuario do github.
                </p>

              </div>
              <div className="card">
                <p className='cardP'>
                  Esse é um exemplo de uma API que foi criada com Next.js.
                </p>
                <p className='cardP'>
                  Uma api que retorna dados de um usuario do github.
                </p>

              </div>
            </div>
          </aside>

        </div>
=======
          <div className="card">
            <div className='card-image'>
            <img
              src={gitResponse.Avatar}
              alt="avatar - Gabriel Fernandes"
              className="avatar"
            />
            </div>
            <h2>{gitResponse.Name} </h2>
            <p>{gitResponse.Bio} </p>
            <p>{gitResponse.Blog} </p>
            <p>{gitResponse.Email} </p>
            <p>repositorios: {gitResponse.public_repos} </p>
            <p>Seguidores: {gitResponse.Followers} </p>
            <p>seguindo: {gitResponse.Following} </p>
          </div>
        </div>
        <aside className="aside">
        <h1
          className="title"
          id="title"
        >
          <a href=''
          onClick={handleClick}
          target="_blank">
             Bem vindo a minha API!
          </a>
        </h1>
        <div className="title">
          <button 
          onClick={handleClick}
          className="button"
          target="_blank">
            Api aqui!
          </button>

        </div>
          <div className="aside-content grid">
            
            <div className="card">
              <p>
                Esse é um exemplo de uma API que foi criada com Next.js.
              </p>
              <p>
                Uma api que retorna dados de um usuario do github.
              </p>
              
            </div>
          </div>
        </aside>
>>>>>>> 6d2190887c09a2151580eff768db34033a086b1b
      </main>

      <footer className="footer">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className="logo">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
