import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


export async function getStaticProps(){
  const github = await fetch('https://api.github.com/users/Gabrielfernandes87f')
  const gitResponse = await github.json()
  return{
    props: {gitResponse}

  }
}

export default function Home({gitResponse}) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bem vindo <a href="https://next-api-liard.vercel.app/api/hello">a minha API!</a>
        </h1>
        <h2> { gitResponse.login } </h2>
        <p className={styles.description}>
          <img src={gitResponse.avatar_url} alt="Gabriel Fernandes" width={200} height={200}/>
          
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
