import Head from 'next/head'
import Image from 'next/image'
import '../styles/Home.module.css'


export async function getStaticProps() {
  const github = await fetch('https://api.github.com/users/Gabrielfernandes87f')
  const gitResponse = await github.json()
  return {
    props: { gitResponse }

  }

}


export default function Home({ gitResponse }) {

  function handleClick() {
    window.location.href = '/api'
  }


  return (
    <div className="container"
    >
      <Head>
        <title>Meu App Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <main className="main">
        <div className="grid">
          <div className="card cardPerfil">
            <div>
              <div className='card-image'>
                <img
                  src={gitResponse.avatar_url}
                  alt="avatar - Gabriel Fernandes"
                  className="avatar"
                />
              </div>
              <div className="cardPerfilContent">
              <h2>{gitResponse.name} </h2>
              <p className='cardP'>{gitResponse.bio} </p>
              <p >{gitResponse.Blog} </p>
              <p>{gitResponse.email} </p>
              <p>repositorios: {gitResponse.public_repos} </p>
              <p>Seguidores: {gitResponse.followers} </p>
              <p>seguindo: {gitResponse.following} </p>
              </div>
            </div>
          </div>
          <aside className="aside">
            <h1
              className="title"
              id="title"
            >
              <a href=''
                onClick={handleClick}
                target="_blank">
                Bem vindo a minha Api!
              </a>
            </h1>
            <div className="title">
              <button
                onClick={handleClick}
                className="button"
                target="_blank">
                Api aqui!
              </button>
            </div>
            <div className="aside-content grid">

              <div className="card card1">
                <p className='cardP'>
                  Esse é um exemplo de uma API que foi criada com Next.js.
                </p>
                <p className='cardP'>
                  Uma api que retorna dados de um usuario do github.
                </p>

              </div>
              <div className="card">
                <p className='cardP'>
                  O objetivo é apresentar um pouco de como utilizar uma api.
                </p>
                <p className='cardP'>
                  Se clicar no botão, Api aqui! você será redirecionado para a api.
                  Parace um codigo quebrado uma api, um sorftware que nao rodou corretamente.
                  Mas se trata de dados json.
                  Aqui eu fiz minha propria Api pegando dados da api do github e depois consumindo minha api pra colocar no meu site.
                  Eu poderia usar logo Api do github, mas ela bloqueia acesso muito rapido a api, devido a quantidade de requisições.
                </p>

              </div>
            </div>
          </aside>

        </div>
      </main>

      <footer className="footer">
        <div className="footer-content">
          <p>
            © {new Date().getFullYear()}, Built with Next.js
            By Gabriel Fernandes
            {` `}
          </p>
        </div>

      </footer>
    </div>
  )
}
